
services:
  php-fpm:
    build:
      context: ./php
    volumes:
      - ../:/var/www/camagru
      - uploads_data:/var/www/camagru/src/public/controllers/uploads
    depends_on:
      - mysql
    networks:
      - camagru-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}

  nginx:
    image: nginx:1.27.3
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/camagru
      - uploads_data:/var/www/camagru/src/public/controllers/uploads
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - camagru-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - camagru-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: ./php
    volumes:
      - ../:/var/www/camagru
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - camagru-network
    command: >
      sh -c "
        echo 'Esperando a que MySQL esté listo...'
        while ! nc -z mysql 3306; do
          sleep 1
        done
        echo 'MySQL is ready, running migrations...'
        php /var/www/camagru/src/config/migrate.php
      "

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - camagru-network

networks:
  camagru-network:
    driver: bridge

volumes:
  mysql_data:
  uploads_data: